"use client";
import { useEffect, useState } from "react";
import type { Locale } from "@/lib/zaf/i18n";
import { intlLocale } from "@/lib/zaf/i18n";
type Asset = { networkScope:"testnet"; assetType:string; assetCode:string; assetIssuer:string|null; amount:number|null; numAccounts:number|null; numTrades:number|null; numLiquidityPools:number|null; numClaimableBalances:number|null; createdAt:string|null; tomlUrl:string|null };
type Payload = { generatedAt:string; networkScope:"testnet"; source:string; available:boolean; count:number; assets:Asset[]; note:string; error:string|null };
function num(value:number|null, locale:Locale){ return value==null||!Number.isFinite(value) ? "—" : value.toLocaleString(intlLocale(locale), { maximumFractionDigits:7 }); }
function label(locale:Locale, value:"Available"|"Limited"|"Native or unspecified issuer"|"Created"){ const labels:Record<typeof value,[string,string,string,string,string,string,string,string,string]>={ Available:["Available","Kullanılabilir","Disponible","可用","Disponibile","Disponible","Verfügbar","Disponível","Доступно"], Limited:["Limited","Sınırlı","Limitado","有限","Limitato","Limité","Begrenzt","Limitado","Ограничено"], "Native or unspecified issuer":["Native or unspecified issuer","Native veya belirtilmemiş issuer","Emisor nativo o no especificado","原生资产或未指定发行方","Emittente nativo o non specificato","Émetteur natif ou non spécifié","Native oder nicht angegebener Aussteller","Emissor nativo ou não especificado","Нативный актив или эмитент не указан"], Created:["Created","Oluşturuldu","Creado","已创建","Creato","Créé","Erstellt","Criado","Создано"] }; const index=locale==="tr"?1:locale==="es"?2:locale==="zh"?3:locale==="it"?4:locale==="fr"?5:locale==="de"?6:locale==="pt"?7:locale==="ru"?8:0; return labels[value][index]; }
export function ZafTestnetAssets({locale,tr}:{locale:Locale;tr:(en:string,trText:string)=>string}){
 const [data,setData]=useState<Payload|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{ let active=true; const load=async()=>{ try{ const response=await fetch("/api/zaf/assets?network=testnet&limit=100",{cache:"no-store"}); const body=await response.json(); if(active)setData(response.ok?body:null); }catch{ if(active)setData(null); }finally{ if(active)setLoading(false); } }; void load(); const id=window.setInterval(()=>void load(),60000); return()=>{active=false;window.clearInterval(id)}; },[]);
 return <section className="mt-5 sm:mt-7">
  <div className="mb-3"><h2 className="text-sm font-semibold text-foreground">{tr("Testnet Assets","Testnet Varlıkları")}</h2><p className="text-[11px] text-muted-foreground">{tr("Publicly observable token and asset records from Pi Testnet Horizon.","Pi Testnet Horizon üzerinden herkese açık gözlemlenebilen token ve varlık kayıtları.")}</p></div>
  <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
   <div className="rounded-xl border border-border bg-card p-3"><div className="text-xl font-bold ty-nums text-foreground">{loading?"…":data?.count??"—"}</div><div className="mt-1 text-[10px] font-medium text-foreground">{tr("Observed Assets","Gözlemlenen Varlıklar")}</div><div className="mt-1 text-[9px] text-muted-foreground">{tr("Current public response","Mevcut herkese açık yanıt")}</div></div>
   <div className="rounded-xl border border-border bg-card p-3"><div className="text-xl font-bold text-foreground">Testnet</div><div className="mt-1 text-[10px] font-medium text-foreground">{tr("Network Scope","Ağ Kapsamı")}</div><div className="mt-1 text-[9px] text-muted-foreground">{data?.generatedAt?new Date(data.generatedAt).toLocaleString(intlLocale(locale)):"—"}</div></div>
   <div className="rounded-xl border border-border bg-card p-3"><div className="text-xl font-bold text-foreground">{data?.available?label(locale,"Available"):label(locale,"Limited")}</div><div className="mt-1 text-[10px] font-medium text-foreground">{tr("Source Status","Kaynak Durumu")}</div></div>
   <div className="rounded-xl border border-border bg-card p-3"><div className="text-xl font-bold text-foreground">Horizon</div><div className="mt-1 text-[10px] font-medium text-foreground">{tr("Observation Source","Gözlem Kaynağı")}</div><div className="mt-1 text-[9px] text-muted-foreground">api.testnet.minepi.com</div></div>
  </div>
  {!data?.available ? <div className="mt-3 rounded-xl border border-border bg-card p-4"><div className="text-xs font-semibold text-foreground">{tr("Testnet Token Observatory","Testnet Token Gözlem Merkezi")}</div><p className="mt-1 text-[10px] leading-relaxed text-muted-foreground">{data?.error??tr("The public Testnet asset source is not currently observable.","Herkese açık Testnet varlık kaynağı şu anda gözlemlenemiyor.")}</p><div className="mt-3 rounded-lg border border-border bg-background p-3 text-[10px] leading-relaxed text-muted-foreground">{tr("Coming Soon target: token discovery, issuer profiles, trustlines, liquidity-pool relations, Launchpad relations and historical asset observations.","Yaklaşan hedef: token keşfi, issuer profilleri, trustline'lar, likidite havuzu ilişkileri, Launchpad ilişkileri ve tarihsel varlık gözlemleri.")}</div></div>:null}
  {data?.available&&data.assets.length ? <div className="mt-3 rounded-xl border border-border bg-card p-4"><div className="text-xs font-semibold text-foreground">{tr("Observed Testnet Assets","Gözlemlenen Testnet Varlıkları")}</div><div className="mt-3 grid gap-2 zaf-desktop-two-up">{data.assets.map(asset=><div key={asset.assetCode+"-"+(asset.assetIssuer??"native")} className="rounded-lg border border-border p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="text-[11px] font-semibold text-foreground">{asset.assetCode}</div><div className="mt-1 break-all text-[9px] text-muted-foreground">{asset.assetIssuer??label(locale,"Native or unspecified issuer")}</div></div><span className="shrink-0 rounded-full border border-border px-2 py-0.5 text-[9px] text-muted-foreground">Testnet</span></div><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4"><div><div className="text-[9px] text-muted-foreground">{tr("Accounts","Hesaplar")}</div><div className="text-[10px] text-foreground">{num(asset.numAccounts,locale)}</div></div><div><div className="text-[9px] text-muted-foreground">{tr("Trades","İşlemler")}</div><div className="text-[10px] text-foreground">{num(asset.numTrades,locale)}</div></div><div><div className="text-[9px] text-muted-foreground">{tr("Liquidity Pools","Likidite Havuzları")}</div><div className="text-[10px] text-foreground">{num(asset.numLiquidityPools,locale)}</div></div><div><div className="text-[9px] text-muted-foreground">{tr("Claimable Balances","Claimable Bakiyeler")}</div><div className="text-[10px] text-foreground">{num(asset.numClaimableBalances,locale)}</div></div></div><div className="mt-2 text-[9px] text-muted-foreground">{asset.createdAt?label(locale,"Created")+": "+new Date(asset.createdAt).toLocaleString(intlLocale(locale)):""}{asset.tomlUrl?<><span className="mx-1">·</span><a href={asset.tomlUrl} target="_blank" rel="noreferrer" className="underline underline-offset-2">{tr("Token Metadata","Token Metadatası")}</a></>:null}</div></div>)}</div></div>:null}
  {data?.available&&!data.assets.length?<div className="mt-3 rounded-xl border border-border bg-card p-4 text-[10px] text-muted-foreground">{tr("The Testnet asset endpoint responded, but no asset records were exposed in this page.","Testnet varlık endpointi yanıt verdi ancak bu sayfada varlık kaydı açığa çıkmadı.")}</div>:null}
  <div className="mt-3 rounded-xl border border-border bg-card p-4 text-[10px] leading-relaxed text-muted-foreground">{tr("Boundary: Test-Pi has no real-world value. Pi documents that Testnet token balances and the Testnet itself may be reset during testing. Asset observations here are read-only snapshots of the public Testnet source.","Sınır: Test-Pi'nin gerçek dünya değeri yoktur. Pi, Testnet token bakiyelerinin ve Testnet'in testler sırasında sıfırlanabileceğini belirtir. Buradaki varlık gözlemleri herkese açık Testnet kaynağının salt-okunur snapshot'larıdır.")}</div>
 </section>;
}