"use client";

import { useEffect, useState, type ReactNode } from "react";
import type { Locale } from "@/lib/zaf/i18n";
import type { ZafSnapshot } from "@/lib/zaf/types";
import { ZafNodeIntelligence } from "@/components/zaf-node-intelligence";
import { ZafNodeHistory } from "@/components/zaf-node-history";

const spanishOverrides: Record<string, string> = {
  "The September 9, 2026 update improved discovery, reliability, and developer tooling.": "La actualización del 9 de septiembre de 2026 mejoró el descubrimiento, la fiabilidad y las herramientas para desarrolladores.",
  "Apps run on the user's own computer, with mobile access through Pi Browser.": "Las aplicaciones se ejecutan en el propio ordenador del usuario, con acceso móvil a través de Pi Browser.",
  "Version 0.6.3 introduced ranking by current running counts.": "La versión 0.6.3 incorporó la clasificación por número actual de ejecuciones.",
  "On August 14, 2026, an initial distributed-computing test was completed with five volunteer Node runners. On August 27, OpenClaw and Atlassian MCP Server were featured.": "El 14 de agosto de 2026 se completó una primera prueba de computación distribuida con cinco operadores de Node voluntarios. El 27 de agosto se destacaron OpenClaw y Atlassian MCP Server.",
  "An end-to-end distributed-computing test was completed through SoloHost.": "Se completó una prueba integral de computación distribuida a través de SoloHost.",
  "The initial test described in the August 14, 2026 official update.": "La prueba inicial descrita en la actualización oficial del 14 de agosto de 2026.",
  "Node operators can opt in to make available computing capacity usable by Terze Parti workloads.": "Los operadores de Node pueden optar por poner su capacidad de cómputo disponible a disposición de cargas de trabajo de terceros.",
  "The official update describes Pi compensation by Terze Parti clients for suitable workloads.": "La actualización oficial describe una compensación en Pi por parte de clientes de terceros para cargas de trabajo adecuadas.",
  "There is no verified live feed for global compute capacity, active workloads, or real-time compute earnings, so ZAF TECH does not fabricate them.": "No existe un flujo en directo verificado sobre la capacidad de cómputo global, las cargas activas o las ganancias de cómputo en tiempo real, por lo que ZAF TECH no inventa esos datos.",
};

function spanishCopy(value:string) {
  return spanishOverrides[value] ?? value;
}
type Resources = {
  host?: { cpuPercent?: number|null; memory?: { usedBytes?: number|null; totalBytes?: number|null; usedPercent?: number|null }; disk?: { drive?: string; usedPercent?: number|null }; network?: { receivedBytes?: number|null; sentBytes?: number|null } }|null;
  docker?: { cpuPercent?: number|null; memory?: { usedBytes?: number|null; limitBytes?: number|null }; network?: { receivedBytes?: number|null; sentBytes?: number|null }; blockIO?: { readBytes?: number|null; writeBytes?: number|null } }|null;
  wsl?: { available?: boolean; distributions?: Array<{ state?: string }> }|null;
};
type Health = { version?: string; supportedProtocols?: number[] };

function bytes(v:number|null|undefined){if(v==null||!Number.isFinite(v))return "—";const u=["B","KB","MB","GB","TB"];let n=v,i=0;while(n>=1024&&i<4){n/=1024;i++;}return n.toFixed(n>=10||i===0?0:1)+" "+u[i];}
function pct(v:number|null|undefined){return v==null||!Number.isFinite(v)?"—":v.toFixed(1)+"%";}
function Card({title,value,detail}:{title:string;value:string;detail:string}){return <div className="rounded-xl border border-border bg-card p-3 sm:p-4"><div className="text-xl font-bold ty-nums text-foreground">{value}</div><div className="mt-1 text-xs font-medium text-foreground">{title}</div><div className="mt-1 text-[11px] leading-relaxed text-muted-foreground">{detail}</div></div>;}
function Source({href,children}:{href:string;children:ReactNode}){return <a href={href} target="_blank" rel="noreferrer" className="text-foreground underline underline-offset-2">{children}</a>;}

function SoloHost({locale}:{locale:Locale}){
 const tr=locale==="tr"; const es=locale==="es"; const zh=locale==="zh"; const it=locale==="it"; const fr=locale==="fr"; const de=locale==="de"; const pt=locale==="pt"; const ru=locale==="ru";
 return <section className="mt-7"><div className="mb-3"><h2 className="text-sm font-semibold text-foreground">{it?"SoloHost":"SoloHost"}</h2><p className="text-[11px] text-muted-foreground">{tr?"Pi Desktop üzerindeki self-hosted uygulama katmanının resmi durumunu ve doğrulanmış kullanım alanlarını gösterir.":it?"Pi Desktop üzerindeki self-hosted uygulama katmanının resmi durumu ve doğrulanmış kullanım alanları.":fr?"État officiel et cas d’utilisation documentés de la couche d’applications auto-hébergées dans Pi Desktop.":zh?"Pi Desktop 上自托管应用层的官方状态和已验证使用场景。":es?spanishCopy("Muestra El Estado Oficial Y Los Casos De Uso Verificados De La Capa De Aplicaciones Self-Hosted En Pi Desktop."):de?"Offizieller Status und dokumentierte Anwendungsfälle der selbst gehosteten Anwendungsschicht in Pi Desktop.":pt?"Status oficial e casos de uso documentados da camada de aplicativos auto-hospedados no Pi Desktop.":ru?"Официальный статус и документированные сценарии использования слоя приложений с самостоятельным хостингом в Pi Desktop.":"Official status and documented use cases of the self-hosted application layer in Pi Desktop."}</p></div>
 <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
 <Card title={tr?"Platform Durumu":it?"Piattaforma":fr?"Statut de la plateforme":zh?"平台状态":es?spanishCopy("Estado De La Plataforma"):de?"Plattformstatus":pt?"Status da Plataforma":ru?"Статус платформы":"Platform Status"} value="Beta" detail={tr?"SoloHost, Pi2Day 2026 ile açık ve permissionless bir framework olarak tanıtıldı.":it?"SoloHost è stato presentato a Pi2Day 2026 come framework aperto e permissionless.":fr?"SoloHost a été présenté à Pi2Day 2026 comme un framework ouvert et sans permission.":zh?"SoloHost 在 Pi2Day 2026 上作为开放、无需许可的框架推出。":es?spanishCopy("SoloHost Se Presentó En Pi2Day 2026 Como Un Framework Abierto Y Sin Permisos."):de?"SoloHost wurde bei Pi2Day 2026 als offenes, erlaubnisfreies Framework vorgestellt.":pt?"O SoloHost foi apresentado no Pi2Day 2026 como um framework aberto e sem permissões.":ru?"SoloHost был представлен на Pi2Day 2026 как открытый фреймворк без разрешений.":"SoloHost was introduced at Pi2Day 2026 as an open, permissionless framework."}/>
 <Card title="Pi Desktop" value="0.6.3" detail={tr?"9 Eylül 2026 güncellemesi keşif, güvenilirlik ve geliştirici araçlarını geliştirdi.":it?"L’aggiornamento del 9 settembre 2026 ha migliorato scoperta, affidabilità e strumenti per sviluppatori.":fr?"La mise à jour du 9 septembre 2026 a amélioré la découverte, la fiabilité et les outils pour développeurs.":zh?"2026 年 9 月 9 日的更新改进了发现、可靠性和开发者工具。":es?spanishCopy("The September 9, 2026 update improved discovery, reliability, and developer tooling."):de?"Das Update vom 9. September 2026 verbesserte Entdeckung, Zuverlässigkeit und Entwicklerwerkzeuge.":pt?"A atualização de 9 de setembro de 2026 melhorou descoberta, confiabilidade e ferramentas para desenvolvedores.":ru?"Обновление от 9 сентября 2026 улучшило обнаружение, надёжность и инструменты разработчика.":"The September 9, 2026 update improved discovery, reliability, and developer tooling."}/>
 <Card title={tr?"Çalıştırma Modeli":it?"Modello Di Esecuzione":fr?"Modèle d’exécution":zh?"运行模式":es?spanishCopy("Modelo De Ejecución"):de?"Ausführungsmodell":pt?"Modelo de Execução":ru?"Модель выполнения":"Execution Model"} value={tr?"Yerel":it?"Local":fr?"Local":zh?"本地":es?spanishCopy("Local"):"Local"} detail={tr?"Uygulamalar kullanıcının kendi bilgisayarında çalışır; mobil erişim Pi Browser üzerinden desteklenir.":zh?"应用在用户自己的电脑上运行，并通过 Pi Browser 支持移动访问。":es?spanishCopy("Apps run on the user's own computer, with mobile access through Pi Browser."):de?"Apps laufen auf dem eigenen Computer des Benutzers; mobiler Zugriff wird über Pi Browser unterstützt.":pt?"Os apps rodam no próprio computador do usuário, com acesso móvel pelo Pi Browser.":ru?"Приложения работают на собственном компьютере пользователя, а мобильный доступ поддерживается через Pi Browser.":"Apps run on the user's own computer, with mobile access through Pi Browser."}/>
 <Card title={tr?"Keşif Sinyali":it?"Segnale Di Scoperta":fr?"Signal de découverte":zh?"发现信号":es?spanishCopy("Señal De Descubrimiento"):de?"Entdeckungssignal":pt?"Sinal de Descoberta":ru?"Сигнал обнаружения":"Discovery Signal"} value={it?"Conteggi Di Esecuzione":fr?"Comptes d’exécution": "Running Counts"} detail={tr?"0.6.3 ile uygulamalar mevcut çalıştırılma sayılarına göre sıralanabiliyor.":zh?"0.6.3 版本引入了按当前运行数量排序的功能。":es?spanishCopy("Version 0.6.3 introduced ranking by current running counts."):de?"Version 0.6.3 führte die Sortierung nach aktuellen Ausführungszahlen ein.":pt?"A versão 0.6.3 introduziu a classificação pelas contagens atuais de execução.":ru?"Версия 0.6.3 добавила ранжирование по текущему числу запусков.":"Version 0.6.3 introduced ranking by current running counts."}/>
 </div>
 <div className="mt-3 rounded-xl border border-border bg-card p-4 text-[11px] leading-relaxed text-muted-foreground"><div className="font-medium text-foreground">{tr?"Son resmi gelişmeler":it?"Ultimi Sviluppi Ufficiali":fr?"Dernières évolutions officielles":zh?"最新官方进展":es?spanishCopy("Últimos Desarrollos Oficiales"):de?"Neueste offizielle Entwicklungen":pt?"Últimos Desenvolvimentos Oficiais":ru?"Последние официальные обновления":"Latest Official Developments"}</div><p className="mt-1">{tr?"14 Ağustos 2026'da beş gönüllü Node runner ile ilk dağıtık hesaplama testi tamamlandı. 27 Ağustos'ta OpenClaw ve Atlassian MCP Server öne çıkan SoloHost uygulamalarına eklendi.":it?"Il 14 agosto 2026 è stato completato il primo test di distributed computing con cinque operatori Node volontari. Il 27 agosto OpenClaw e Atlassian MCP Server sono stati inclusi tra le app SoloHost in evidenza.":fr?"Le 14 août 2026, un premier test de calcul distribué a été réalisé avec cinq opérateurs Node volontaires. Le 27 août, OpenClaw et Atlassian MCP Server ont été mis en avant parmi les applications SoloHost.":zh?"2026 年 8 月 14 日，五名志愿 Node 运行者完成了首次分布式计算测试。8 月 27 日，OpenClaw 和 Atlassian MCP Server 被列为重点 SoloHost 应用。":es?spanishCopy("On August 14, 2026, an initial distributed-computing test was completed with five volunteer Node runners. On August 27, OpenClaw and Atlassian MCP Server were featured."):de?"Am 14. August 2026 wurde ein erster Distributed-Computing-Test mit fünf freiwilligen Node-Betreibern abgeschlossen. Am 27. August wurden OpenClaw und Atlassian MCP Server hervorgehoben.":pt?"Em 14 de agosto de 2026, um teste inicial de computação distribuída foi concluído com cinco operadores voluntários de Node. Em 27 de agosto, OpenClaw e Atlassian MCP Server foram destacados.":ru?"14 августа 2026 года был завершён первый тест распределённых вычислений с пятью добровольными операторами Node. 27 августа были представлены OpenClaw и Atlassian MCP Server.":"On August 14, 2026, an initial distributed-computing test was completed with five volunteer Node runners. On August 27, OpenClaw and Atlassian MCP Server were featured."}</p><div className="mt-2 flex flex-wrap gap-3"><Source href="https://minepi.com/blog/solohost-pi-desktop-0-6-3/">Pi Desktop 0.6.3</Source><Source href="https://minepi.com/blog/pi-node-0-6-2/">Node 0.6.2 / Compute Test</Source><Source href="https://minepi.com/blog/new-solohost-apps/">SoloHost Apps</Source></div></div>
 </section>;
}

function Compute({locale}:{locale:Locale}){
 const tr=locale==="tr"; const es=locale==="es"; const zh=locale==="zh"; const it=locale==="it"; const fr=locale==="fr"; const de=locale==="de"; const pt=locale==="pt"; const ru=locale==="ru";
 return <section className="mt-7"><div className="mb-3"><h2 className="text-sm font-semibold text-foreground">{fr?"Calcul":it?"Calcolo":zh?"计算":es?spanishCopy("Cómputo"):de?"Computing":pt?"Computação":ru?"Вычисления":"Compute"}</h2><p className="text-[11px] text-muted-foreground">{tr?"Pi Node kaynaklarının blockchain dışında hesaplama amacıyla kullanımına ilişkin resmi durum.":it?"Stato ufficiale dell’utilizzo delle risorse Pi Node per il calcolo oltre l’infrastruttura blockchain.":fr?"État officiel de l’utilisation des ressources Pi Node pour le calcul au-delà de l’infrastructure blockchain.":zh?"Pi Node 资源用于区块链基础设施之外计算的官方状态。":es?spanishCopy("Estado Oficial Del Uso De Recursos De Pi Node Para Cómputo Más Allá De La Infraestructura Blockchain."):de?"Offizieller Status der Nutzung von Pi-Node-Ressourcen für Computing über die Blockchain-Infrastruktur hinaus.":pt?"Status oficial do uso de recursos do Pi Node para computação além da infraestrutura blockchain.":ru?"Официальный статус использования ресурсов Pi Node для вычислений за пределами блокчейн-инфраструктуры.":"Official status of using Pi Node resources for computing beyond blockchain infrastructure."}</p></div>
 <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
 <Card title={tr?"Kullanım Durumu":it?"Stato Di Utilizzo":fr?"État d’utilisation":zh?"使用状态":es?spanishCopy("Estado De Uso"):de?"Nutzungsstatus":pt?"Status de Uso":ru?"Статус использования":"Use-Case Status"} value={tr?"Test edildi":it?"Testato":fr?"Testé":zh?"已测试":es?spanishCopy("Probado"):de?"Getestet":pt?"Testado":ru?"Протестировано":"Tested"} detail={tr?"SoloHost üzerinden gerçek cihazlarla uçtan uca dağıtık hesaplama testi yapıldı.":it?"È stato completato un test di distributed computing end-to-end tramite SoloHost.":fr?"Un test de calcul distribué de bout en bout a été réalisé via SoloHost.":zh?"通过 SoloHost 完成了一次端到端分布式计算测试。":es?spanishCopy("An end-to-end distributed-computing test was completed through SoloHost."):de?"Über SoloHost wurde ein End-to-End-Test für verteiltes Computing abgeschlossen.":pt?"Um teste de computação distribuída de ponta a ponta foi concluído pelo SoloHost.":ru?"Через SoloHost был проведён сквозной тест распределённых вычислений.":"An end-to-end distributed-computing test was completed through SoloHost."}/>
 <Card title={tr?"Test Katılımcıları":it?"Partecipanti Al Test":fr?"Participants au test":zh?"测试参与者":es?spanishCopy("Participantes De La Prueba"):de?"Testteilnehmer":pt?"Participantes do Teste":ru?"Участники теста":"Test Participants"} value="5" detail={tr?"14 Ağustos 2026 resmi duyurusundaki ilk test.":it?"Il primo test descritto nell’aggiornamento ufficiale del 14 agosto 2026.":fr?"Premier test décrit dans la mise à jour officielle du 14 août 2026.":zh?"2026 年 8 月 14 日官方更新中介绍的首次测试。":es?spanishCopy("The initial test described in the August 14, 2026 official update."):de?"Der erste Test aus dem offiziellen Update vom 14. August 2026.":pt?"O teste inicial descrito na atualização oficial de 14 de agosto de 2026.":ru?"Первый тест, описанный в официальном обновлении от 14 августа 2026 года.":"The initial test described in the August 14, 2026 official update."}/>
 <Card title={tr?"Kaynak Modeli":it?"Modello Delle Risorse":fr?"Modèle de ressources":zh?"资源模式":es?spanishCopy("Modelo De Recursos"):de?"Ressourcenmodell":pt?"Modelo de Recursos":ru?"Модель ресурсов":"Resource Model"} value="Opt-in" detail={tr?"Node operatörleri kullanılabilir hesaplama kapasitesini üçüncü taraf iş yüklerine açmayı seçebilir.":it?"Gli operatori Node possono scegliere di rendere disponibile la capacità di calcolo disponibile per workload di terze parti.":fr?"Les opérateurs Node peuvent choisir de mettre leur capacité de calcul disponible à disposition de charges de travail tierces.":zh?"Node 运营者可以选择将可用计算容量提供给第三方工作负载。":es?spanishCopy("Node operators can opt in to make available computing capacity usable by Terze Parti workloads."):de?"Node-Betreiber können ihre verfügbare Rechenkapazität für Workloads Dritter freigeben.":pt?"Operadores de Node podem optar por disponibilizar sua capacidade de computação para cargas de trabalho de terceiros.":ru?"Операторы Node могут по желанию предоставлять доступную вычислительную мощность для сторонних рабочих нагрузок.":"Node operators can opt in to make available computing capacity usable by Terze Parti workloads."}/>
 <Card title={tr?"Ücretlendirme Modeli":it?"Modello Di Compensazione":fr?"Modèle de compensation":zh?"补偿模式":es?spanishCopy("Modelo De Compensación"):de?"Vergütungsmodell":pt?"Modelo de Compensação":ru?"Модель компенсации":"Compensation Model"} value={tr?"Üçüncü taraf":it?"Terze Parti":fr?"Tiers":zh?"第三方":es?spanishCopy("Terceros"):de?"Drittanbieter":pt?"Terceiros":ru?"Третья сторона":"Third-party"} detail={tr?"Resmi açıklama uygun iş yüklerinde Pi ile telafi modelini tanımlıyor.":it?"L’aggiornamento ufficiale descrive una compensazione in Pi da parte di clienti Terze Parti per workload appropriati.":fr?"La mise à jour officielle décrit une compensation en Pi par des clients tiers pour les charges de travail appropriées.":zh?"官方更新说明，符合条件的工作负载可由第三方客户使用 Pi 进行补偿。":es?spanishCopy("The official update describes Pi compensation by Terze Parti clients for suitable workloads."):de?"Das offizielle Update beschreibt eine Vergütung in Pi durch Drittanbieter für geeignete Workloads.":pt?"A atualização oficial descreve compensação em Pi por clientes terceiros para cargas de trabalho adequadas.":ru?"Официальное обновление описывает компенсацию в Pi со стороны сторонних клиентов за подходящие рабочие нагрузки.":"The official update describes Pi compensation by Terze Parti clients for suitable workloads."}/>
 </div>
 <div className="mt-3 rounded-xl border border-border bg-card p-4 text-[11px] leading-relaxed text-muted-foreground"><div className="font-medium text-foreground">{tr?"ZAF TECH Sınırı":it?"Limite Di ZAF TECH":fr?"Limite de ZAF TECH":zh?"ZAF TECH 边界":es?spanishCopy("Límite De ZAF TECH"):de?"ZAF-TECH-Grenze":pt?"Limite da ZAF TECH":ru?"Граница ZAF TECH":"ZAF TECH Boundary"}</div><p className="mt-1">{tr?"Küresel compute kapasitesi, aktif iş yükleri veya gerçek zamanlı compute kazançları için doğrulanmış bir veri akışı yok; bu nedenle ZAF TECH bunları uydurmuyor.":it?"Non esiste un feed live verificato per la capacità di calcolo globale, i workload attivi o i guadagni di calcolo in tempo reale; ZAF TECH non inventa questi dati.":fr?"Il n’existe pas de flux en direct vérifié pour la capacité de calcul mondiale, les charges actives ou les revenus de calcul en temps réel ; ZAF TECH n’invente pas ces données.":zh?"目前没有经过验证的全球计算容量、活跃工作负载或实时计算收益数据流，因此 ZAF TECH 不会虚构这些数据。":es?spanishCopy("There is no verified live feed for global compute capacity, active workloads, or real-time compute earnings, so ZAF TECH does not fabricate them."):de?"Es gibt keinen verifizierten Live-Feed für globale Rechenkapazität, aktive Workloads oder Echtzeit-Computing-Einnahmen; ZAF TECH erfindet diese Daten nicht.":pt?"Não existe um feed ao vivo verificado para capacidade global de computação, cargas ativas ou ganhos de computação em tempo real; a ZAF TECH não inventa esses dados.":ru?"Нет проверенного потока в реальном времени для глобальной вычислительной мощности, активных нагрузок или доходов от вычислений; ZAF TECH не выдумывает эти данные.":"There is no verified live feed for global compute capacity, active workloads, or real-time compute earnings, so ZAF TECH does not fabricate them."}</p><div className="mt-2"><Source href="https://minepi.com/blog/openmind-case-study/">Pi Node Decentralized Computing Case Study</Source></div></div>
 </section>;
}

function Infrastructure({locale}:{locale:Locale}){
 const tr=locale==="tr"; const es=locale==="es"; const zh=locale==="zh"; const it=locale==="it"; const fr=locale==="fr"; const de=locale==="de"; const pt=locale==="pt"; const ru=locale==="ru";const[health,setHealth]=useState<Health|null>(null);const[r,setR]=useState<Resources|null>(null);const[online,setOnline]=useState<boolean|null>(null);
 useEffect(()=>{const load=async()=>{try{const[h,x]=await Promise.all([fetch("http://127.0.0.1:39100/health",{cache:"no-store"}),fetch("http://127.0.0.1:39100/resources",{cache:"no-store"})]);if(!h.ok)throw new Error();setHealth(await h.json());setR(x.ok?await x.json():null);setOnline(true);}catch{setHealth(null);setR(null);setOnline(false);}};void load();const id=window.setInterval(()=>void load(),15000);return()=>window.clearInterval(id);},[]);
 const dist=r?.wsl?.distributions?.filter(d=>d.state==="running").length??0;
 return <section className="mt-7"><div className="mb-3"><h2 className="text-sm font-semibold text-foreground">{fr?"Infrastructure":it?"Infrastruttura":zh?"基础设施":es?spanishCopy("Infraestructura"):de?"Infrastruktur":pt?"Infraestrutura":ru?"Инфраструктура":"Infrastructure"}</h2><p className="text-[11px] text-muted-foreground">{tr?"Yerel Connector, Docker ve WSL kaynak gözlemleri.":it?"Osservazioni delle risorse del Connector locale, Docker e WSL.":fr?"Observations des ressources du Connector local, de Docker et de WSL.":zh?"本地 Connector、Docker 和 WSL 资源观测。":es?spanishCopy("Observaciones De Recursos Del Connector Local, Docker Y WSL."):de?"Beobachtungen der Ressourcen von lokalem Connector, Docker und WSL.":pt?"Observações de recursos do Connector local, Docker e WSL.":ru?"Наблюдения ресурсов локального Connector, Docker и WSL.":"Local Connector, Docker, and WSL resource observations."}</p></div>
 <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
 <Card title="Connector" value={online?(tr?"Bağlı":it?"Connesso":fr?"Connecté":zh?"已连接":es?spanishCopy("Conectado"):de?"Verbunden":pt?"Conectado":ru?"Подключён":"Connected"):(tr?"Çevrimdışı":it?"Offline":fr?"Hors ligne":zh?"离线":es?spanishCopy("Fuera De Línea"):de?"Offline":pt?"Offline":ru?"Офлайн":"Offline")} detail={health?.version?(tr?"Sürüm ":it?"Versione ":fr?"Version ":zh?"版本 ":es?spanishCopy("Versión "):de?"Version ":pt?"Versão ":ru?"Версия ":"Version ")+health.version:"127.0.0.1:39100"}/>
 <Card title="CPU" value={pct(r?.host?.cpuPercent)} detail={tr?"Host CPU Kullanımı":it?"Utilizzo CPU Host":fr?"Utilisation du CPU hôte":zh?"主机 CPU 使用率":es?spanishCopy("Uso De CPU Del Host"):de?"CPU-Auslastung des Hosts":pt?"Uso de CPU do Host":ru?"Использование CPU хоста":"Host CPU usage"}/>
 <Card title={tr?"Bellek":it?"Memoria":fr?"Mémoire":zh?"内存":es?spanishCopy("Memoria"):de?"Arbeitsspeicher":pt?"Memória":ru?"Память":"Memory"} value={pct(r?.host?.memory?.usedPercent)} detail={r?.host?.memory?bytes(r.host.memory.usedBytes)+" / "+bytes(r.host.memory.totalBytes):"—"}/>
 <Card title="Disk" value={pct(r?.host?.disk?.usedPercent)} detail={r?.host?.disk?.drive??"C:"}/>
 <Card title="Docker" value={pct(r?.docker?.cpuPercent)} detail={r?.docker?.memory?bytes(r.docker.memory.usedBytes)+" / "+bytes(r.docker.memory.limitBytes):(tr?"Container Kaynak Kullanımı":it?"Utilizzo Delle Risorse Del Container":fr?"Utilisation des ressources du conteneur":zh?"容器资源使用率":es?spanishCopy("Uso De Recursos Del Contenedor"):de?"Ressourcennutzung des Containers":pt?"Uso de Recursos do Container":ru?"Использование ресурсов контейнера":"Container Resource Usage")}/>
 <Card title="WSL" value={r?.wsl?.available?String(dist):"—"} detail={tr?"Çalışan Dağıtımlar":it?"Distribuzioni In Esecuzione":fr?"Distributions en cours d’exécution":zh?"正在运行的发行版":es?spanishCopy("Distribuciones En Ejecución"):de?"Laufende Distributionen":pt?"Distribuições em Execução":ru?"Запущенные дистрибутивы":"Running Distributions"}/>
 </div>
 <div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2"><div className="rounded-xl border border-border bg-card p-4 text-[11px]"><div className="font-medium text-foreground">{tr?"Connector protokol desteği":it?"Supporto Del Protocollo Del Connector":fr?"Prise en charge du protocole du Connector":zh?"Connector 协议支持":es?spanishCopy("Compatibilidad Del Protocolo Del Connector"):de?"Connector-Protokollunterstützung":pt?"Suporte ao Protocolo do Connector":ru?"Поддержка протокола Connector":"Connector Protocol Support"}</div><div className="mt-1 text-muted-foreground">{health?.supportedProtocols?.length?health.supportedProtocols.map(p=>"v"+p).join(" · "):"—"}</div><div className="mt-2 text-muted-foreground">{tr?"Connector salt-okunur çalışır ve Docker'ı uzaktan açmaz.":it?"Il Connector funziona in modalità di sola lettura e non espone Docker da remoto.":fr?"Le Connector fonctionne en lecture seule et n’expose pas Docker à distance.":zh?"Connector 以只读模式运行，不会远程暴露 Docker。":es?spanishCopy("El Connector Funciona En Modo De Solo Lectura Y No Expone Docker De Forma Remota."):de?"Der Connector arbeitet schreibgeschützt und stellt Docker nicht remote bereit.":pt?"O Connector funciona somente para leitura e não expõe o Docker remotamente.":ru?"Connector работает только для чтения и не предоставляет удалённый доступ к Docker.":"The Connector is read-only and does not expose Docker remotely."}</div></div><div className="rounded-xl border border-border bg-card p-4 text-[11px]"><div className="font-medium text-foreground">{tr?"Ağ Ve Container I/O":it?"I/O Di Rete E Container":fr?"E/S réseau et conteneur":zh?"网络与容器 I/O":es?spanishCopy("E/S De Red Y Contenedor"):de?"Netzwerk- und Container-I/O":pt?"I/O de Rede e Container":ru?"Сетевой I/O и I/O контейнера":"Network And Container I/O"}</div><div className="mt-1 text-muted-foreground">Host: {bytes(r?.host?.network?.receivedBytes)} ↓ · {bytes(r?.host?.network?.sentBytes)} ↑</div><div className="mt-1 text-muted-foreground">Docker: {bytes(r?.docker?.network?.receivedBytes)} ↓ · {bytes(r?.docker?.network?.sentBytes)} ↑</div><div className="mt-1 text-muted-foreground">Block I/O: {bytes(r?.docker?.blockIO?.readBytes)} ↓ · {bytes(r?.docker?.blockIO?.writeBytes)} ↑</div></div></div>
 </section>;
}

export function ZafNodeCompute({locale,data,subtab}:{locale:Locale;data:ZafSnapshot|null;subtab:string}){if(subtab==="Node History")return <ZafNodeHistory locale={locale}/>;if(subtab==="SoloHost")return <SoloHost locale={locale}/>;if(subtab==="Compute")return <Compute locale={locale}/>;if(subtab==="Infrastructure")return <Infrastructure locale={locale}/>;return <ZafNodeIntelligence locale={locale} data={data}/>;}
